title: Project

pages: false

fields:
  tab_1:
    label:
      cs: Obecné
      en: General
    type: tabs
  title:
    label:
      cs: Název
      en: Title
    type: text
    width: 1/2
  general_cover:
    label:
      cs: Hlavní fotka
      en: Cover Image
    type: image
    width: 1/2
  general_category:
    label:
      cs: Kategorie
      en: Category
    type: select
    options:
      design:
        cs: Projekce
        en: Design Engineering
      execution:
        cs: Realizace
        en: Work Execution
      site:
        cs: Stavební Engineering
        en: Site Engineering

  tab_2:
    label: Detail
    type: tabs
  detail_headline:
    label:
      cs: Nadpis
      en: Headline
    type: textarea
    buttons: false
  detail_text:
    label:
      cs: Popis
      en: Description
    type: textarea
    buttons: false
  detail_services:
    label:
      cs: Poskytnuté služby
      en: Services
    type: textarea
    width: 1/2
    buttons:
      - link
      - ulist
  detail_completed:
    label:
      cs: Rok dokončení
      en: Year Completed
    type: number
    width: 1/2

  tab_3:
    label: Media
    type: tabs
  detail_media:
    label: Media
    type: builder
    fieldsets:
      full:
        label: Velká fotka
        entry: >
          <img src="{{_fileUrl}}{{image}}" width="100%">
        fields:
          image:
            label: Fotka
            type: image
      split:
        label: Fotky vedle sebe
        entry: >
          <img src="{{_fileUrl}}{{image_1}}" width="49%" style="vertical-align: top">
          <img src="{{_fileUrl}}{{image_2}}" width="49%" style="vertical-align: top">
        fields:
          image_1:
            label: Fotka nalevo
            type: image
          image_2:
            label: Fotka napravo
            type: image
      video:
        label: Fotka a video
        entry: >
          <img src="{{_fileUrl}}{{image}}" width="49%" style="vertical-align: top">
          <iframe src="{{video}}" width="49%" height="300px" frameborder="0">
        fields:
          image:
            label: Fotka
            type: image
          video:
            label: Adresa videa
            type: text
