title: Project

pages: false

fields:
  tab_1:
    label: General
    type: tabs
  title:
    label: Title
    type: text
    width: 1/2
  general_cover:
    label: Cover Image
    type: image
    width: 1/2
  general_category:
    label: Category
    type: select
    options:
      design: Design Engineering
      execution: Work Execution
      site: Site Engineering

  tab2:
    label: Detail
    type: tabs
  detail_headline:
    label: Headline
    type: textarea
    buttons: false
  detail_text:
    label: Description
    type: textarea
    buttons: false
  detail_services:
    label: Services
    type: textarea
    width: 1/2
    buttons:
      - link
      - ulist
  detail_completed:
    label: Year Completed
    type: number
    width: 1/2
  detail_media:
    label: Media
    type: builder
    fieldsets:
      full:
        label: Full Image
        fields:
          image:
            label: Image
            type: image
      split:
        label: Split Images
        fields:
          image_1:
            label: Image
            type: image
          image_2:
            label: Image
            type: image
      video:
        label: Image and Video
        fields:
          image:
            label: Image
            type: image
          video:
            label: Video URL
            type: text
