title: Service

pages:
  template: service-info

fields:
  tab_1:
    label:
      cs: Obecné
      en: General
    type: tabs
  title:
    label:
      cs: Název
      en: Title
    type: text
    width: 1/2
  general_thumb:
    label:
      cs: Náhledová fotka
      en: Thumbnail
    type: image
    translate: false
    width: 1/2
  general_text:
    label:
      cs: Popis
      en: Description
    type: textarea
    buttons: false
  general_caption:
    label:
      cs: Text tlačítka
      en: Button Caption
    type: text
    width: 1/2
  general_related:
    label:
      cs: Související reference
      en: Related Project
    type: select
    width: 1/2
    options: query
    query:
      page: projects

  tab_2:
    label: Detail
    type: tabs
  detail_headline:
    label:
      cs: Nadpis
      en: Headline
    type: textarea
    width: 1/2
    buttons: false
  detail_image:
    label:
      cs: Fotografie
      en: Image
    type: image
    translate: false
    width: 1/2
  detail_text:
    label: Text
    type: textarea
    buttons: false
  detail_facts:
    label:
      cs: Fakta
      en: Facts
    type: structure
    limit: 3
    entry: >
      {{facts_number}}{{facts_suffix}} {{facts_caption}}
    fields:
      facts_number:
        label:
          cs: Číslo
          en: Number
        type: number
      facts_suffix:
        label:
          cs: Přípona
          en: Suffix
        type: text
      facts_caption:
        label:
          cs: Popisek
          en: Caption
        type: text
  detail_features_title:
    label:
      cs: Nadpis výhod
      en: Features Title
    type: text
  detail_features:
    label:
      cs: Výhody
      en: Features
    type: structure
    limit: 3
    entry: >
      {{features_title}}<br>
      {{features_text}}
    fields:
      features_icon:
        label:
          cs: Ikona
          en: Icon
        type: image
        translate: false
      features_title:
        label:
          cs: Název
          en: Title
        type: text
      features_text:
        label: Text
        type: textarea
        buttons: false
  detail_infobox_title:
    label:
      cs: Nadpis informačních bloků
      en: Information Blocks Title
    type: text
