title: Site

fields:
  title:
    label:
      cs: Název
      en: Title
    type:  text

  partners:
    label:
      cs: Partneři
      en: Partners
    type: gallery

  colophon:
    label:
      cs: Tiráž
      en: Colophon
    type: text
